/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addAdressbuch.java
 *
 * Created on 29.12.2011, 20:18:42
 */
package netzwerkverwaltung;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author manfred.fischer
 */
public class addAdressbuch extends javax.swing.JFrame {

    private ClientNetzwerk clients;
    private newStoerung stoerung;
    private HauptBildschirm haupt;
    private String FID = "";

    /** Creates new form addAdressbuch */
    public addAdressbuch(ClientNetzwerk cl, newStoerung st, HauptBildschirm haupt) {
        stoerung = st;
        this.haupt = haupt;
        initComponents();
        clients = cl;
        this.setLocationRelativeTo(haupt);
    }
    private Boolean newAdressFirmaInfo = false;

    public void newAdressFirma(String name, String vorname) {
        fHinzufuegen.setText("Firma Hinzufuegen");

        if (name == null && vorname == null) {
            newAdressFirmaInfo = false;
            if (name != null) {
                pName.setText(name);
            }
            if (vorname != null) {
                pvName.setText(vorname);
            }
        } else {
            newAdressFirmaInfo = true;
        }

        this.setVisible(true);

    }

    public void newNetzAdresse() {
        fHinzufuegen.setText("add Netz-Standort");
        auswahl.removeTabAt(1);
        this.setVisible(true);

    }

    private Boolean newPersonBoolean = false;

    public void newAdressPersonInfo(String vorname, String Nachname, String ID) {
        auswahl.remove(0);
        fHinzufuegen.setText("Person Hinzufuegen");
        FID = ID;
        this.setVisible(true);
        if (Nachname != null) {
            pName.setText(Nachname);
        }
        if (vorname != null) {
            pvName.setText(vorname);
        }
        newPersonBoolean = true;
    }

    public void newAdressPerson(String FID) {
        this.FID = FID;
        fHinzufuegen.setText("Person Hinzufuegen");
        auswahl.removeTabAt(0);
        this.setVisible(true);
    }

    public void startAdressFirma(ArrayList<String> datenFirma) {
        String[] txt = datenFirma.get(0).split("<>");
        auswahl.remove(1);
        String inhaltFirma = txt[0];
        for (int i = 1; i < txt.length; i++) {
            inhaltFirma = inhaltFirma + "\n" + txt[i];
        }
        fID.setText(datenFirma.get(1));
        fName.setText(datenFirma.get(2));
        sStrasse.setText(datenFirma.get(3));
        aOrt.setText(datenFirma.get(4));
        aPLZ.setText(datenFirma.get(5));
        aInhalt.setText(inhaltFirma);
        fHinzufuegen.setText("Firma Bearbeiten");
        FID = fID.getText();
        this.setVisible(true);
    }

    public void startAdressPerson(ArrayList<String> datenPerson, String F) {
        String inhaltT = "";
        FID = F;
        String[] txt = datenPerson.get(6).toString().split("<>");
        inhaltT = txt[0];
        for (int i = 1; i < txt.length; i++) {
            inhaltT = inhaltT + "\n" + txt[i];
        }
        pID.setText(datenPerson.get(0).toString());
        pName.setText(datenPerson.get(1).toString());
        pvName.setText(datenPerson.get(2).toString());
        pAbtl.setText(datenPerson.get(3).toString());
        pTel.setText(datenPerson.get(4).toString());
        pFax.setText(datenPerson.get(5).toString());
        pHandy.setText(datenPerson.get(9).toString());
        pEMail.setText(datenPerson.get(8).toString());
        pInhalt.setText(inhaltT);
        fHinzufuegen.setText("Person Bearbeiten");
        auswahl.removeTabAt(0);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        auswahl = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        aInhalt = new javax.swing.JTextArea();
        aPLZ = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        aOrt = new javax.swing.JTextField();
        sStrasse = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        pvName = new javax.swing.JTextField();
        pName = new javax.swing.JTextField();
        pFax = new javax.swing.JTextField();
        pTel = new javax.swing.JTextField();
        pAbtl = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        pEMail = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        pInhalt = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        pHandy = new javax.swing.JTextField();
        fHinzufuegen = new javax.swing.JButton();
        fID = new javax.swing.JTextField();
        pID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adressbuch");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(133, 133, 149));

        jLabel31.setText("PLZ:");

        jLabel30.setText("Strasse:");

        jLabel29.setText("FirmenNamen:");

        jLabel32.setText("Ort:");

        aInhalt.setColumns(17);
        aInhalt.setRows(2);
        jScrollPane5.setViewportView(aInhalt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fName)
                            .addComponent(sStrasse, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aPLZ)
                            .addComponent(aOrt))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31))
                    .addComponent(aPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(sStrasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32))
                    .addComponent(aOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );

        auswahl.addTab("Firma", jPanel1);

        jPanel2.setBackground(new java.awt.Color(133, 133, 149));

        jLabel38.setText("Fax.:");

        jLabel36.setText("Abteilung:");

        jLabel35.setText("Vorname:");

        jLabel37.setText("Tel.:");

        jLabel34.setText("Name:");

        jLabel43.setText("eMail:");

        pInhalt.setColumns(18);
        pInhalt.setLineWrap(true);
        pInhalt.setRows(3);
        jScrollPane6.setViewportView(pInhalt);

        jLabel39.setText("Handy:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pAbtl, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(pvName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel43))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(pEMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(pHandy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(pvName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pAbtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(pEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pHandy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addContainerGap())
        );

        auswahl.addTab("Person", jPanel2);

        fHinzufuegen.setText("Firma hinzufügen");
        fHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fHinzufuegenActionPerformed(evt);
            }
        });

        fID.setEditable(false);
        fID.setVisible(false);

        pID.setEditable(false);
        pID.setVisible(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(auswahl)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fHinzufuegen)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(auswahl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fHinzufuegen)
                    .addComponent(fID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearFirma() {
        fName.setText("");
        sStrasse.setText("");
        aPLZ.setText("");
        aOrt.setText("");
        aInhalt.setText("");

    }

    private void ClearPerson() {

        pAbtl.setText("");
        pEMail.setText("");
        pFax.setText("");
        pID.setText("");
        pInhalt.setText("");
        pvName.setText("");
        pTel.setText("");
        pName.setText("");
    }

    private void FirmaHinzufuegen() {
        try {
            String[] txt = aInhalt.getText().split("\\n");
            String inhaltFirma = txt[0];
            for (int i = 1; i < txt.length; i++) {
                inhaltFirma = inhaltFirma + "<>" + txt[i];
            }
            if (fHinzufuegen.getText().equals("Firma Bearbeiten")) {
                ArrayList<String> datenSend = new ArrayList<String>();
                if (fName.getText().equals("")) {
                    JOptionPane.showMessageDialog(new JFrame(), "Bitte einen FirmenNamen angeben Danke!");
                } else {
                    datenSend.add("2002"+clients.trennzeichen+ "AdressbuchFirma"+clients.trennzeichen+ "FirmenNamen"+clients.trennzeichen + clients.checkDaten(fName.getText()) + ""+clients.trennzeichen+ "AdressbuchFirm"+clients.trennzeichen+ "" + fID.getText());
                    datenSend.add("2002"+clients.trennzeichen+ "AdressbuchFirma"+clients.trennzeichen+ "Strasse"+clients.trennzeichen + clients.checkDaten(sStrasse.getText()) + ""+clients.trennzeichen+ "AdressbuchFirm"+clients.trennzeichen+ "" + fID.getText());
                    datenSend.add("2002"+clients.trennzeichen+ "AdressbuchFirma"+clients.trennzeichen+ "PLZ"+clients.trennzeichen + clients.checkDaten(aPLZ.getText()) + ""+clients.trennzeichen+ "AdressbuchFirm"+clients.trennzeichen+ "" + fID.getText());
                    datenSend.add("2002"+clients.trennzeichen+ "AdressbuchFirma"+clients.trennzeichen+ "Ort"+clients.trennzeichen + clients.checkDaten(aOrt.getText()) + ""+clients.trennzeichen+ "AdressbuchFirm"+clients.trennzeichen+ "" + fID.getText());
                    datenSend.add("2002"+clients.trennzeichen+ "AdressbuchFirma"+clients.trennzeichen+ "Hinweis"+clients.trennzeichen + clients.checkDaten(inhaltFirma) + ""+clients.trennzeichen+ "AdressbuchFirm"+clients.trennzeichen+ "" + fID.getText());
                    clients.ClientVersand(datenSend);
                }
            } else {
                if (fName.getText().equals("")) {
                    JOptionPane.showMessageDialog(new JFrame(), "Bitte einen FirmenNamen angeben Danke!");
                } else {
                    
                    clients.send("1903"+clients.trennzeichen + fName.getText() + ""+clients.trennzeichen + clients.checkDaten(sStrasse.getText()) + ""+clients.trennzeichen + clients.checkDaten(aPLZ.getText()) + ""+clients.trennzeichen
                            + clients.checkDaten(aOrt.getText()) + ""+clients.trennzeichen + clients.checkDaten(inhaltFirma));
                    getIDAdressbuch();
                    if (pvName.getText().equals("") && pName.getText().equals("")) {
                        clients.send("1902"+clients.trennzeichen+ "Zentrale"+clients.trennzeichen + "Zentrale (" + fName.getText() + ")+---+---+---+---"+clients.trennzeichen + IDAdressbuch + "+---+---+---+---");
                    } else {
                        ArrayList<ArrayList<String>> DatenAdresseT = (ArrayList<ArrayList<String>>) clients.netzwerkVerwaltung.getAdressbuchFirma("-1","addAdressbuch/FirmaHinzufügen",false).clone();
                        for (int i = 0; i < DatenAdresseT.size(); i++) {
                            if (DatenAdresseT.get(i).get(1).equals(fName.getText())) {
                                addPerson(DatenAdresseT.get(i).get(8).toString());
                                break;
                            }
                        }
                    }
                }

            }
            if (!newAdressFirmaInfo) {
                clearFirma();
                ClearPerson();
                
            } else {
                stoerung.change = false;
                getIDAdressbuchPerson();
                stoerung.searchUser.setText("");
                stoerung.cbFirma.removeAllItems();
                stoerung.cbFirma.addItem(fName.getText());
                stoerung.IDAdressbuch = IDAdressbuchPerson;
                stoerung.cbFirmaPerson.removeAllItems();
                stoerung.cbFirmaPerson.addItem(pvName.getText() + ", " + pName.getText());
                this.setVisible(false);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e);
        }
    }


     private void StandortHinzufuegen() {
        try {
            String[] txt = aInhalt.getText().split("\\n");
            String inhaltFirma = txt[0];
            for (int i = 1; i < txt.length; i++) {
                inhaltFirma = inhaltFirma + "<>" + txt[i];
            }

                if (fName.getText().equals("")) {
                    JOptionPane.showMessageDialog(new JFrame(), "Bitte einen FirmenNamen angeben Danke!");
                } else {

                    clients.send("1904"+clients.trennzeichen + fName.getText() + ""+clients.trennzeichen + clients.checkDaten(sStrasse.getText()) + ""+clients.trennzeichen + clients.checkDaten(aPLZ.getText()) + ""+clients.trennzeichen
                            + clients.checkDaten(aOrt.getText()) + ""+clients.trennzeichen + clients.checkDaten(inhaltFirma));

                }
                clearFirma();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e);
        }
    }

    private void fHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fHinzufuegenActionPerformed
        if (fHinzufuegen.getText().equals("add Netz-Standort")){
            StandortHinzufuegen();

        } else if (fHinzufuegen.getText().startsWith("Firma")) {
            FirmaHinzufuegen();
        } else {
            PersonHinzufuegen();
        }
        
    }//GEN-LAST:event_fHinzufuegenActionPerformed

    private String IDAdressbuch = "0", IDAdressbuchPerson = "0";

    private void getIDAdressbuchPerson() {
        ArrayList<ArrayList<String>> DatenAdresseT = (ArrayList<ArrayList<String>>) clients.netzwerkVerwaltung.getAdressbuchPerson("-1", IDAdressbuch,"addAdressbuch/getIDAdressbuchPerson",false).clone();
        for (int i = 0; i < DatenAdresseT.size(); i++) {
            if (DatenAdresseT.get(i).get(1).equals(pName.getText()) && DatenAdresseT.get(i).get(2).equals(pvName.getText())) {
                IDAdressbuchPerson = DatenAdresseT.get(i).get(8).toString();
                break;
            }
        }
    }

    private void getIDAdressbuch() {
        ArrayList<ArrayList<String>> DatenAdresseT = (ArrayList<ArrayList<String>>) clients.netzwerkVerwaltung.getAdressbuchFirma("-1","addAdressbuch/getIDAdressbuch",false).clone();
        for (int i = 0; i < DatenAdresseT.size(); i++) {
            if (DatenAdresseT.get(i).get(1).equals(fName.getText())) {
                IDAdressbuch = DatenAdresseT.get(i).get(0).toString();
                break;
            }
        }
    }

    private void PersonHinzufuegen() {
        try {

            String[] txt = pInhalt.getText().split("\\n");
            String inhaltFirma = txt[0];
            for (int i = 1; i < txt.length; i++) {
                inhaltFirma = inhaltFirma + "<>" + txt[i];
            }
            if (fHinzufuegen.getText().equals("Person Bearbeiten")) {
                ArrayList<String> datenSend = new ArrayList<String>();
                datenSend.add("2002"+clients.trennzeichen+ "Adressbuch"+clients.trennzeichen+ "Name"+clients.trennzeichen + clients.checkDaten(pName.getText()) + ""+clients.trennzeichen+ "IDAdressbuch"+clients.trennzeichen + pID.getText());
                datenSend.add("2002"+clients.trennzeichen+ "Adressbuch"+clients.trennzeichen+ "Vorname"+clients.trennzeichen + clients.checkDaten(pvName.getText()) + ""+clients.trennzeichen+ "IDAdressbuch"+clients.trennzeichen + pID.getText());
                datenSend.add("2002"+clients.trennzeichen+ "Adressbuch"+clients.trennzeichen+ "Abteilung"+clients.trennzeichen + clients.checkDaten(pAbtl.getText()) + ""+clients.trennzeichen+ "IDAdressbuch"+clients.trennzeichen + pID.getText());
                datenSend.add("2002"+clients.trennzeichen+ "Adressbuch"+clients.trennzeichen+ "Tel"+clients.trennzeichen + clients.checkDaten(pTel.getText()) + ""+clients.trennzeichen+ "IDAdressbuch"+clients.trennzeichen + pID.getText());
                datenSend.add("2002"+clients.trennzeichen+ "Adressbuch"+clients.trennzeichen+ "Handy"+clients.trennzeichen + clients.checkDaten(pHandy.getText()) + ""+clients.trennzeichen+ "IDAdressbuch"+clients.trennzeichen + pID.getText());
                datenSend.add("2002"+clients.trennzeichen+ "Adressbuch"+clients.trennzeichen+ "Fax"+clients.trennzeichen + clients.checkDaten(pFax.getText()) + ""+clients.trennzeichen+ "IDAdressbuch"+clients.trennzeichen + pID.getText());
                datenSend.add("2002"+clients.trennzeichen+ "Adressbuch"+clients.trennzeichen+ "Hinweis"+clients.trennzeichen + clients.checkDaten(inhaltFirma) + ""+clients.trennzeichen+ "IDAdressbuch"+clients.trennzeichen + pID.getText());
                datenSend.add("2002"+clients.trennzeichen+ "Adressbuch"+clients.trennzeichen+ "eMail"+clients.trennzeichen + clients.checkDaten(pEMail.getText()) + ""+clients.trennzeichen+ "IDAdressbuch"+clients.trennzeichen + pID.getText());
                clients.ClientVersand(datenSend);
                this.setVisible(false);
                this.dispose();
            } else {
                addPerson(FID);
                if (newPersonBoolean) {
                    IDAdressbuch = FID;
                    stoerung.cbFirmaPerson.removeAllItems();
                    stoerung.cbFirmaPerson.addItem(pName.getText() + ", " + pvName.getText());
                    stoerung.searchUser.setText("");
                    getIDAdressbuchPerson();
                    stoerung.IDAdressbuch = IDAdressbuchPerson;
                    this.setVisible(false);
                    this.dispose();
                } else {
                    ClearPerson();
                }
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex);
        }
    }

    private void addPerson(String FirmaID) {
        String[] txt = pInhalt.getText().split("\\n");
        String inhaltFirma = txt[0];
        for (int i = 1; i < txt.length; i++) {
            inhaltFirma = inhaltFirma + "<>" + txt[i];
        }
        clients.send("1902"+clients.trennzeichen + clients.checkDaten(pvName.getText()) + ""+clients.trennzeichen
                + clients.checkDaten(pName.getText()) + ""+clients.trennzeichen
                + clients.checkDaten(pAbtl.getText()) + ""+clients.trennzeichen
                + clients.checkDaten(pTel.getText()) + ""+clients.trennzeichen
                + clients.checkDaten(pFax.getText()) + ""+clients.trennzeichen
                + clients.checkDaten(inhaltFirma) + ""+clients.trennzeichen
                + clients.checkDaten(FirmaID) + ""+clients.trennzeichen
                + clients.checkDaten(pEMail.getText())+ ""+clients.trennzeichen
                + clients.checkDaten(pHandy.getText()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aInhalt;
    private javax.swing.JTextField aOrt;
    private javax.swing.JTextField aPLZ;
    private javax.swing.JTabbedPane auswahl;
    private javax.swing.JButton fHinzufuegen;
    private javax.swing.JTextField fID;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField pAbtl;
    private javax.swing.JTextField pEMail;
    private javax.swing.JTextField pFax;
    private javax.swing.JTextField pHandy;
    private javax.swing.JTextField pID;
    private javax.swing.JTextArea pInhalt;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pTel;
    private javax.swing.JTextField pvName;
    private javax.swing.JTextField sStrasse;
    // End of variables declaration//GEN-END:variables
}
