/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Einstellungen.java
 *
 * Created on 29.12.2011, 09:17:09
 */
package netzwerkverwaltung;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manfred.fischer
 */
public class Einstellungen extends javax.swing.JFrame {

    private String[] titles = new String[]{"SoftwareName", "Zuständige", "eMail"};
    private String[] titles2 = new String[]{"PfadName", "Pfad"};
    private DefaultTableModel tableZustaendigkeit = new DefaultTableModel(titles, 0), tablePfad = new DefaultTableModel(titles2, 0);

    private String checkDaten(String Check) {
        if (Check.equals("")) {
            Check = "---";
        }
        String tm="";
        String[] temp = Check.split("");
        for (int i=0;i<temp.length;i++){
            if (temp[i].equals("\\+")){
              tm = tm + "-?-";  
            }else{
              tm = tm + temp[i]; 
            }
        }
        return tm;
    }
    
    /** Creates new form Einstellungen */
    public Einstellungen() {
        initComponents();
        JTable tabZustaendigkeit = new JTable(tableZustaendigkeit);
        JTable tabPfad = new JTable(tablePfad);

        ADSScrollPfad.add(tabPfad);
        ADSScrollPfad.setViewportView(tabPfad);

        zustaendigkeiten.add(tabZustaendigkeit);
        zustaendigkeiten.setViewportView(tabZustaendigkeit);
        try {
            BufferedReader read = null;
            read = new BufferedReader(new FileReader(new File("Config/netz.cfg")));
            String DatenTemp = read.readLine();
            while (DatenTemp != null) {
                if (DatenTemp.startsWith("##Server")) {
                    DatenTemp = read.readLine();
                    ServerIP.setText(DatenTemp.substring(4).split(":")[0]);
                    ServerPort.setText(DatenTemp.substring(4).split(":")[1]);
                }
                if (DatenTemp.startsWith("##Zeiten")) {
                    DatenTemp = read.readLine();
                    timeHaupt.setText(DatenTemp.substring(8));
                    DatenTemp = read.readLine();
                    timeStoerung.setText(DatenTemp.substring(8));
                }
                DatenTemp = read.readLine();
            }
            read.close();
            read = new BufferedReader(new FileReader(new File("Config/config.cfg")));
            DatenTemp = read.readLine();
            while (DatenTemp != null) {
                if (DatenTemp.startsWith("##ADS Einstellungen")) {
                    DatenTemp = read.readLine();
                    ADSServer.setText(DatenTemp.substring(13));
                    DatenTemp = read.readLine();
                    ADSUser.setText(DatenTemp.substring(15));
                    DatenTemp = read.readLine();
                    ADSPW.setText(DatenTemp.substring(13));
                }
                if (DatenTemp.startsWith("##ADS Pfad")) {
                    DatenTemp = read.readLine();
                    while(!DatenTemp.startsWith("##")){
                      Object[] temp = new Object[2];
                      temp[0]=DatenTemp.split("Pfad: ")[0].substring(10);
                      temp[1]=DatenTemp.split("Pfad: ")[1];
                      tablePfad.addRow(temp); 
                      DatenTemp = read.readLine();
                    }
                }
                if (DatenTemp.startsWith("##Zuständigkeit")) {
                    DatenTemp = read.readLine();
                    while(DatenTemp != null){
                      Object[] temp = new Object[3];
                      temp[0]=DatenTemp.split("Zustaendige: ")[0].substring(6);
                      temp[1]=DatenTemp.split("Zustaendige: ")[1].split(" eMail: ")[0];
                      temp[2]=DatenTemp.split("Zustaendige: ")[1].split(" eMail: ")[1];
                      tablePfad.addRow(temp); 
                      DatenTemp = read.readLine();
                    }
                }
                DatenTemp = read.readLine();
            }
            read.close();
        } catch (Exception ex) {
        }

        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        zustaendigkeiten = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        ADSServer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ADSPfad = new javax.swing.JTextField();
        ADSGruppenNamen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ADSPW = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ADSScrollPfad = new javax.swing.JScrollPane();
        ADSUser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        timeStoerung = new javax.swing.JTextField();
        timeHaupt = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        ServerPort = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        ServerIP = new javax.swing.JTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zuständigkeiten:");

        jLabel3.setText("Server IP:");

        jLabel4.setText("Windows ADS:");

        jLabel6.setText("Pfad:");

        jLabel5.setText("User:");

        jLabel7.setText("PW:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(zustaendigkeiten, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addContainerGap(308, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ADSUser, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ADSPW, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ADSServer, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ADSScrollPfad, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ADSGruppenNamen, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ADSPfad, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))))
                            .addGap(7, 7, 7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zustaendigkeiten, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ADSServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ADSUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ADSPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ADSScrollPfad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADSGruppenNamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADSPfad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Beantragen", jPanel1);

        timeStoerung.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        timeStoerung.setText("5");
        timeStoerung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStoerungActionPerformed(evt);
            }
        });

        timeHaupt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        timeHaupt.setText("5");
        timeHaupt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeHauptActionPerformed(evt);
            }
        });

        jTextField3.setText("/Protokolle/");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel19.setText("------------------------------- Störung / User---------------------------------------------");

        jLabel21.setText("Speicher Ort:");

        jLabel18.setText("Aktualisierung der Informationen (min):");

        jLabel16.setText("------------------------------- Haupt ------------------------------------------------------");

        jLabel20.setText("------------------------------- Protokolierung -------------------------------------------");

        jLabel17.setText("Aktualisierung der Informationen (min):");

        jLabel22.setText("------------------------------- Server ------------------------------------------------------");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Server Empfang");

        jLabel15.setText("Server Port: ");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Server Versand");

        ServerPort.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ServerPort.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ServerPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerPortActionPerformed(evt);
            }
        });

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Server Störungen");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Server Adresse:");

        jCheckBox4.setSelected(true);
        jCheckBox4.setText("Client Störungen");

        ServerIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ServerIP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ServerIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerIPActionPerformed(evt);
            }
        });

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("New User Eintrag");

        jCheckBox6.setSelected(true);
        jCheckBox6.setText("Chat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeHaupt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeStoerung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox3))))
                        .addGap(51, 51, 51)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(timeHaupt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(timeStoerung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Einstellungen", jPanel2);

        jButton2.setText("Speichern");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object[] temp = new Object[2];
    temp[0] = ADSGruppenNamen.getText();
    temp[1] = ADSPfad.getText();
    
    tablePfad.addRow(temp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void timeStoerungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStoerungActionPerformed
    }
// TODO add your handling code here:}//GEN-LAST:event_timeStoerungActionPerformed

        private void timeHauptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeHauptActionPerformed
        }
// TODO add your handling code here:}//GEN-LAST:event_timeHauptActionPerformed

        private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        }
// TODO add your handling code here:}//GEN-LAST:event_jTextField3ActionPerformed

        private void ServerPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerPortActionPerformed
        }
// TODO add your handling code here:}//GEN-LAST:event_ServerPortActionPerformed

        private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        }
// TODO add your handling code here:}//GEN-LAST:event_jCheckBox3ActionPerformed

        private void ServerIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerIPActionPerformed
        }
// TODO add your handling code here:}//GEN-LAST:event_ServerIPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
        BufferedWriter schreib = new BufferedWriter(new FileWriter(new File("Daten/netz.cfg")));
        schreib.write("##Server\n");
        schreib.append("IP: " + checkDaten(ServerIP.getText()) + ":" + checkDaten(ServerPort.getText()) + "\n");
        schreib.write("##Zeiten\n");
        schreib.append("Haupt.: " + checkDaten(timeHaupt.getText()) + "\n");
        schreib.append("Stoer.: " + checkDaten(timeStoerung.getText()) + "\n");
        BufferedWriter schreib2 = new BufferedWriter(new FileWriter(new File("Daten/config.cfg")));
        schreib2.write("##ADS Einstellungen\n");
        schreib2.append("ADSServer IP: " + checkDaten(ADSServer.getText()) + "\n");
        schreib2.append("ADSServer User: " + checkDaten(ADSUser.getText()) + "\n");
        schreib2.append("ADSServer PW: " + checkDaten(ADSPW.getText()) + "\n");
        schreib2.append("##ADS Pfad:\n");
        for (int i = 0; i < tablePfad.getRowCount(); i++) {
            schreib2.append("ADS: Name: " + checkDaten(tablePfad.getValueAt(i, 0).toString()) + "Pfad: " + checkDaten(tablePfad.getValueAt(i, 1).toString()) + "\n");
        }
        schreib2.append("##Zuständigkeit:\n");
        for (int i = 0; i < tableZustaendigkeit.getRowCount(); i++) {
            schreib2.append("Name: " + checkDaten(tableZustaendigkeit.getValueAt(i, 0).toString()) + "Zustaendige: " + checkDaten(tableZustaendigkeit.getValueAt(i, 1).toString()) +" eMail: " + checkDaten(tableZustaendigkeit.getValueAt(i, 2).toString()) + "\n");
        }
        

        schreib2.close();
        schreib.close();
        JOptionPane.showMessageDialog(new JFrame(), "Config Datei geschrieben.... :) \nBitte Neustarten damit die Einstellungen Angewendet werden!!!");
        this.setVisible(false);
        this.dispose();
    } catch (IOException ex) {
    }
    }//GEN-LAST:event_jButton2ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADSGruppenNamen;
    private javax.swing.JTextField ADSPW;
    private javax.swing.JTextField ADSPfad;
    private javax.swing.JScrollPane ADSScrollPfad;
    private javax.swing.JTextField ADSServer;
    private javax.swing.JTextField ADSUser;
    private javax.swing.JTextField ServerIP;
    private javax.swing.JTextField ServerPort;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField timeHaupt;
    private javax.swing.JTextField timeStoerung;
    private javax.swing.JScrollPane zustaendigkeiten;
    // End of variables declaration//GEN-END:variables
}
