/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newEmail.java
 *
 * Created on 31.12.2011, 12:08:35
 */
package netzwerkverwaltung;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author manfred.fischer
 */
public class newEmail extends javax.swing.JFrame {

    private ClientNetzwerk clients;
    private int UID;
    private String[] titles = new String[]{"Name"};
    private JTable tabAnhaenge;
    private HashMap UInfo;
    private TabelFont tableAnhaenge = new TabelFont();
    private ArrayList<File> anhaengeFile = new ArrayList<File>();
    private HTMLEditorKit kit = new HTMLEditorKit();

    /** Creates new form newEmail */
    public newEmail(HashMap UserInfo, ClientNetzwerk cl) {
        initComponents();
        initActions();
        UInfo = UserInfo;
        tabAnhaenge = tableAnhaenge.getTable(titles, -1, null, -1, null);
        anhaenge.add(tabAnhaenge);
        anhaenge.setViewportView(tabAnhaenge);
        tabAnhaenge.setFillsViewportHeight(true);
        tabAnhaenge.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getButton() == 3) {
                    JFileChooser fcF = new JFileChooser();
                    fcF.setDialogTitle("Select folder");
                    fcF.setFileSelectionMode(JFileChooser.FILES_ONLY);
                    if (fcF.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                        File datei = fcF.getSelectedFile();
                        ArrayList<String> info = new ArrayList<String>();
                        info.add(datei.getName());
                        tableAnhaenge.getInfoTable.addRow(info, "-1");
                        anhaengeFile.add(datei);
                    }
                }
            }
        });
        clients = cl;
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        an = new javax.swing.JTextField();
        bbc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        betreff = new javax.swing.JTextField();
        anhaenge = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btUnderlined = new javax.swing.JToggleButton();
        btCenter = new javax.swing.JToggleButton();
        schriftArt = new javax.swing.JComboBox();
        size = new javax.swing.JComboBox();
        btBold = new javax.swing.JToggleButton();
        btRight = new javax.swing.JToggleButton();
        btLeft = new javax.swing.JToggleButton();
        btItalic = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        selectColor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("new eMail");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        text.setContentType("text/html");
        text.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n  \n    </p>\r\n  </body>\r\n</html>\r\n");
        jScrollPane3.setViewportView(text);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netzwerkverwaltung/Bilder/k.jpg"))); // NOI18N
        jLabel4.setText("An..");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netzwerkverwaltung/Bilder/k.jpg"))); // NOI18N
        jLabel5.setText("Cc..");

        an.setText("manfred.fischer@dbschenker.com");

        jLabel6.setText("Betreff:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(betreff, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                    .addComponent(bbc, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                    .addComponent(an, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(bbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betreff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btUnderlined.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btUnderlined.setText("U");
        btUnderlined.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btUnderlined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnderlinedActionPerformed(evt);
            }
        });

        btCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netzwerkverwaltung/Bilder/Text-align-center-icon.png"))); // NOI18N
        btCenter.setBorder(null);
        btCenter.setBorderPainted(false);

        schriftArt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        size.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "10", "12", "14", "18", "24", "36", "48" }));
        size.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });

        btBold.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btBold.setText("F");
        btBold.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netzwerkverwaltung/Bilder/Text-align-right-icon.png"))); // NOI18N
        btRight.setBorder(null);
        btRight.setBorderPainted(false);

        btLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netzwerkverwaltung/Bilder/Text-align-left-icon.png"))); // NOI18N
        btLeft.setBorder(null);
        btLeft.setBorderPainted(false);

        btItalic.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        btItalic.setText("K");
        btItalic.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jButton3.setText("Send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        selectColor.setText("Farbe");
        selectColor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(7, 7, 7)
                .addComponent(schriftArt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectColor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUnderlined, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBold, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btItalic, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCenter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRight)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(schriftArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectColor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btUnderlined, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBold, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btItalic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btCenter)
                    .addComponent(btRight)
                    .addComponent(btLeft))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anhaenge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anhaenge, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu2.setText("Datei");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Bearbeiten");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList<File> Dateien = new ArrayList<File>();
        ArrayList<String> DateiN = new ArrayList<String>();
        String  Name;
        String DateiName="";
        String Datum = new SimpleDateFormat("dd.MM.yyyy HH:MM:SS").format(new Date()); 
        
        try {   
            System.setProperty("file.encoding", "UTF8");
            DateiName = "mail-"+Datum+".txt";
            Name = "Temp/"+DateiName;
            File file = new File(Name);
            Writer out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file), "UTF8"));
            out.append(text.getText());
            out.flush();
            out.close();
            anhaengeFile.add(file);
            
            
            clients.sendDateiStoerung(anhaengeFile, (UID+100000),0,"");
            
            
        } catch (Exception e) {
        }




        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void btUnderlinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnderlinedActionPerformed
    }//GEN-LAST:event_btUnderlinedActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
    }//GEN-LAST:event_sizeActionPerformed

    private void initActions() {
        ActionListener a;


        Font[] fonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts();
        ArrayList fontList = new ArrayList(50);
        for (int i = 0; i < fonts.length; i++) {
            if (!fontList.contains(fonts[i].getFamily())) {
                fontList.add(fonts[i].deriveFont(12.0f));
            }
        }
        fonts = new Font[fontList.size()];
        fontList.toArray(fonts);
        schriftArt.removeAllItems();
        for (int i = 0; i < fonts.length; i++) {
            schriftArt.addItem(fonts[i]);
        }

        schriftArt.setFont(fonts[0]);
        schriftArt.setRenderer(new DefaultListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Font font = (Font) value;
                JLabel label = (JLabel) super.getListCellRendererComponent(list, font.getFamily(), index, isSelected, cellHasFocus);
                label.setFont(font);
                return label;
            }
        });

        schriftArt.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                javax.swing.text.StyledEditorKit.FontFamilyAction action = new javax.swing.text.StyledEditorKit.FontFamilyAction("xxx", ((Font) schriftArt.getSelectedItem()).getFamily());
                schriftArt.setFont((Font) schriftArt.getSelectedItem());
                action.actionPerformed(new ActionEvent(schriftArt, ActionEvent.ACTION_PERFORMED, "xxx"));
            }
        });

        size.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                javax.swing.text.StyledEditorKit.FontSizeAction action = new javax.swing.text.StyledEditorKit.FontSizeAction("font-size", Integer.parseInt(size.getSelectedItem().toString()) + 5);
                action.actionPerformed(new ActionEvent(size, ActionEvent.ACTION_PERFORMED, "font-size"));
            }
        });

        selectColor.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                HTMLEditorKit.ForegroundAction action;
                CustomDialog test = new CustomDialog(new JFrame(), true);
                action = new HTMLEditorKit.ForegroundAction("set-foreground", test.getAnswer());
                action.actionPerformed(new ActionEvent(selectColor, ActionEvent.ACTION_PERFORMED, "set-foreground"));
            }
        });

        
        a = new HTMLEditorKit.BoldAction();
        btBold.addActionListener(a);

        //Italic
        a = new HTMLEditorKit.ItalicAction();
        btItalic.addActionListener(a);

        //Underlined
        a = new HTMLEditorKit.UnderlineAction();
        btUnderlined.addActionListener(a);

        //Left
        a = new HTMLEditorKit.AlignmentAction("left", 0);
        btLeft.addActionListener(a);

        //Center
        a = new HTMLEditorKit.AlignmentAction("center", 1);
        btCenter.addActionListener(a);

        //right        
        a = new HTMLEditorKit.AlignmentAction("right", 2);
        btRight.addActionListener(a);


        a = new HTMLEditorKit.ForegroundAction("set-foreground-black", Color.black);


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField an;
    private javax.swing.JScrollPane anhaenge;
    private javax.swing.JTextField bbc;
    private javax.swing.JTextField betreff;
    private javax.swing.JToggleButton btBold;
    private javax.swing.JToggleButton btCenter;
    private javax.swing.JToggleButton btItalic;
    private javax.swing.JToggleButton btLeft;
    private javax.swing.JToggleButton btRight;
    private javax.swing.JToggleButton btUnderlined;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox schriftArt;
    private javax.swing.JButton selectColor;
    private javax.swing.JComboBox size;
    private javax.swing.JTextPane text;
    // End of variables declaration//GEN-END:variables
}
